#import "/templates/book.typ": book

#show: book.with(
  title: "AWS 入門",
  author: "aoki-taquan",
)

#include "chapters/01-はじめに.typ"
#include "chapters/02-アカウント開設と初期設定.typ"
#include "chapters/03-IAM.typ"
#include "chapters/04-VPC.typ"
#include "chapters/05-EC2.typ"
#include "chapters/06-S3.typ"
#include "chapters/07-データベース.typ"
#include "chapters/08-コンテナとサーバーレス.typ"
#include "chapters/09-運用と監視.typ"
#include "chapters/10-セキュリティとコスト管理.typ"
#include "chapters/11-IaCと運用Tips.typ"
#include "chapters/12-Route53とCloudFront.typ"
#include "chapters/13-追加ストレージ.typ"
#include "chapters/14-メッセージングと統合.typ"
#include "chapters/15-ストリーミングとデータ分析.typ"
#include "chapters/16-機械学習と生成AI.typ"
#include "chapters/17-認証サービス詳細.typ"
#include "chapters/18-ネットワーク詳細.typ"
#include "chapters/19-セキュリティサービス詳細.typ"
#include "chapters/20-マルチアカウント運用.typ"
#include "chapters/21-移行とデータ転送.typ"
#include "chapters/22-IoTとメディア.typ"
#include "chapters/23-アーキテクチャパターン集.typ"
#include "chapters/24-ハンズオン静的サイトとサーバーレスAPI.typ"
#include "chapters/25-ハンズオン3層Webアプリ.typ"
#include "chapters/26-ハンズオンデータレイク基礎.typ"
#include "chapters/27-ディザスタリカバリ.typ"
#include "chapters/28-WellArchitectedFramework.typ"
#include "chapters/29-認定資格と学習リソース.typ"
#include "chapters/30-Lambda深掘り.typ"
#include "chapters/31-DynamoDBとNoSQL設計.typ"
#include "chapters/32-ECSとEKS深掘り.typ"
#include "chapters/33-Aurora深掘り.typ"
#include "chapters/34-コスト最適化とFinOps.typ"
#include "chapters/35-可観測性とSRE.typ"
#include "chapters/36-AWSの最新動向と次の一歩.typ"
#include "chapters/37-ハンズオン生成AIアプリ.typ"
#include "chapters/38-CloudFormationとCDK詳細.typ"
#include "chapters/39-Terraform詳細.typ"
#include "chapters/40-CICDとDevOps.typ"
#include "chapters/41-マルチテナントSaaS設計.typ"
#include "chapters/42-AWSチートシート.typ"
#include "chapters/43-性能チューニング完全ガイド.typ"
#include "chapters/44-トラブルシューティングCookbook.typ"
#include "chapters/45-ハイブリッドクラウド.typ"
#include "chapters/46-AWSと関連OSSエコシステム.typ"
